### ISSUE TITLE
shops from vorp_character do not work anymore

### ISSUE THREAD

**Issue by VarusXX** [VORPCORE/vorp_core-lua#150]
**Describe the issue**
After I updated vorp_core to V2.7 the shops comming with vorp_character didn't work anymore. There is no prompt and no NPC but the blip is working.

**To Reproduce**
Just replaced the core to 2.7. Later I renamed it, so it will not be ensured and started the old core 2.6 and it works fine
**Expected behavior**
Just that when I go to clothing store a prompt to enter should be shown.

**Comment by outsider31000** [comment]
they work just fine.
![image](https://github.com/user-attachments/assets/0c9155b7-1c9b-433c-ae8a-b73bef08bd74)
and the shops arent in vorp core.
