### ISSUE TITLE
Deprecated api? 

### ISSUE THREAD

**Issue by yaboibutt3r** [VORPCORE/vorp_core-lua#151]
this is the first time I've noticed this on server startup. I haven't found any apparent issues with this message yet but would like to at least bring it up cause i have no idea what it could be referring to since i have the most recent update of vorp core

[    script:vorp_core] JUST A WARNING: this are deprecated API please refer to api docs to use new ones.

**Comment by outsider31000** [comment]
its saying one of your scripts is using OLD API this is just a warning. you can ignore or contact the devs to use the new.
